### ISSUE TITLE
Add ability to read from stdin

### ISSUE THREAD

**Issue by Miserlou** [techtonik/sha1#1]
It's be nice to be able to `"asdf" | sha1` or even just `sha1 "asdf"`.

**Comment by techtonik** [comment]
1. `"asdf" | sha1` - how to detect that there is some input waiting in stdin? Right now `sha1` without params outputs help. It should be possible to do something like `"asdf" | sha --`
2. `sha1 "asdf"` is not possible, because it treats "asdf" as filename

**Comment by techtonik** [comment]
@Miserlou hopefully all issues with reading from stdin are fixed in https://pypi.python.org/pypi/sha1/1.2

**Comment by Miserlou** [comment]
Excellent, thank you!

(Although I should admit that I wrote my own replacement in the meantime, maybe you'll find that useful too: https://github.com/Miserlou/omnihash )

**Comment by techtonik** [comment]
Yea, I saw that. Too many dependencies to my liking. =)

**Comment by techtonik** [comment]
Added a pointer to omnihash to README.md so that people could discover it.

**Comment by Miserlou** [comment]
Cool! Thanks!!
